version: '2'

services:
    phpapache:
      build: ./php
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - mysql
      volumes:
        - ./www:/var/www/html
    mysql:
      build: ./mysql
      ports:
        - "3306:3306"
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: storage
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      volumes:
        - ./mysql/data:/var/lib/mysql
        #- ./mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080