version: '2'

services:
    phpapache:
      build: ./php
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - mysql
      volumes:
        - ./html:/var/www/html
        - ../certbot/letsencrypt:/etc/letsencrypt
        - ./php/default.conf:/etc/apache2/sites-available/000-default.conf
    mysql:
      image: mariadb
      ports:
        - "3306:3306"
      restart: always
      volumes:
        - mysql_data:/var/lib/mysql
        - ./mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: storage
        MYSQL_USER: root123
        MYSQL_PASSWORD: root123
        TZ: Asia/Taipei
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
volumes: 
  mysql_data: