version: '2'

services:
    phpapache:
      build: ./php
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - mysql
      volumes:
        - ./html:/var/www/html
        - /etc/letsencrypt:/etc/letsencrypt
        - ./php/default.conf:/etc/apache2/sites-available/000-default.conf
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        
    mysql:
      image: mariadb
      ports:
        - "3306:3306"
      restart: always
      volumes:
        - mysql_data:/var/lib/mysql
        - ./mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        TZ: Asia/Taipei
    adminer:
      image: adminer:4.2.5-standalone
      restart: always
      depends_on:
        - mysql
      ports:
        - 8080:8080
volumes: 
  mysql_data:
